/**
 * Enum representing the image sources for various products.
 *
 * Each enum value corresponds to a product and its associated image source.
 * The enum keys are named as 'Product' followed by a unique identifier, and the values are the paths to the product images.
 */
export enum ProductImgSrc {
  Product1 = "/images/products/gala-apples.jpg",
  Product2 = "/images/products/ground-beef.jpg",
  Product3 = "/images/products/organic-milk.jpg",
  Product4 = "/images/products/fresh-broccoli.jpg",
  Product5 = "/images/products/large-eggs.jpg",
  Product6 = "/images/products/wholemeal-bread.jpg",
  Product7 = "/images/products/salmon-fillet.jpg",
  Product8 = "/images/products/bananas.jpg",
  Product9 = "/images/products/spinach.jpg",
  Product10 = "/images/products/orange-juice.jpg",
  Product11 = "/images/products/new-potatoes.jpg",
  Product12 = "/images/products/pasta.jpg",
  Product13 = "/images/products/canned-tomatoes.jpg",
  Product14 = "/images/products/avocado.jpg",
  Product15 = "/images/products/teabags.jpg",
  Product16 = "/images/products/cheddar.jpg",
  Product17 = "/images/products/strawberries.jpg",
  Product18 = "/images/products/chicken-breasts.jpg",
  Product19 = "/images/products/butter.jpg",
  Product20 = "/images/products/carrots.jpg",
  Product21 = "/images/products/red-apples.jpg",
  Product22 = "/images/products/beef-steak.jpg",
  Product23 = "/images/products/organic-whole-milk.jpg",
  Product24 = "/images/products/cauliflower.jpg",
  Product25 = "/images/products/eggs.jpg",
  Product26 = "/images/products/multigrain-bread.jpg",
  Product27 = "/images/products/haddock.jpg",
  Product28 = "/images/products/english-bananas.jpg",
  Product29 = "/images/products/asparagus.jpg",
  Product30 = "/images/products/fresh-orange-juice.jpg",
  Product31 = "/images/products/waxy-potatoes.jpg",
  Product32 = "/images/products/tagliatelle.jpg",
  Product33 = "/images/products/beans.jpg",
  Product34 = "/images/products/kiwi.jpg",
  Product35 = "/images/products/earl-grey.jpg",
  Product36 = "/images/products/stilton.jpg",
  Product37 = "/images/products/raspberries.jpg",
  Product38 = "/images/products/chicken-thighs.jpg",
  Product39 = "/images/products/salted-butter.jpg",
  Product40 = "/images/products/parsnips.jpg",
  Product41 = "/images/products/peas.jpg",
  Product42 = "/images/products/british-strawberries.jpg",
  Product43 = "/images/products/organic-eggs.jpg",
  Product44 = "/images/products/white-bread.jpg",
  Product45 = "/images/products/smoked-salmon.jpg",
  Product46 = "/images/products/cucumbers.jpg",
  Product47 = "/images/products/lemons.jpg",
  Product48 = "/images/products/english-breakfast-tea.jpg",
  Product49 = "/images/products/red-leicester.jpg",
  Product50 = "/images/products/blueberries.jpg",
}